name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    - lecture/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install Python dependencies
      run: |
        pip install -r requirements_python.txt

    - name: Set up IRkernel for R in jupyter
      run: |
        if (!requireNamespace("IRkernel", quietly=TRUE)) install.packages("IRkernel", repos="https://cloud.r-project.org/")
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Install R dependencies
      run: |
        reqs <- readLines("requirements_r.txt")
        for (r in reqs) {
          if (!requireNamespace(r, quietly=TRUE)) install.packages(r, repos="https://cloud.r-project.org/")
        }
      shell: Rscript {0}
    
    - name: Set up Rprofile
      run: |
        opt <- c("", "options(repr.plot.width=5, repr.plot.height=4)")
        profile_loc <- file.path(R.home(component="etc"), "Rprofile.site")
        writeLines(opt, profile_loc)
      shell: Rscript {0}

    # Build the page
    - name: Build the book
      run: |
        jupyter-book build lecture/
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./lecture/_build/html
